//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowAppsChevron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkDataArray_Table
    {
        public int id_link { get; set; }
        public string workflowName { get; set; }
        public Nullable<int> from { get; set; }
        public Nullable<int> to { get; set; }
        public string fromPort { get; set; }
        public string toPort { get; set; }
        public string points { get; set; }
        public string wm { get; set; }
    }
}
