//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowAppsChevron.Models
{
    using System;
    using System.Collections.Generic;

    public partial class NodeDataArray_Table
    {
        public int id { get; set; }
        public string processName { get; set; }
        public string subjectProcess { get; set; }
        public string statusNode { get; set; }
        public string workflowName { get; set; }
        public string loc { get; set; }
        public string pic { get; set; }
        public string startProcess { get; set; }
        public string dueProcess { get; set; }
        public string cycleProcess { get; set; }
        public string comment { get; set; }
        public Nullable<int> key { get; set; }
        public string wm { get; set; }

        //public int intCycleProcess
        //{

        //    get { return Int32.Parse(((this.cycleProcess).Remove(this.cycleProcess.Length - 5))); }

        //}

        //public int a {
        //    //get { return Int32.Parse(DateTime.Parse(this.startProcess)).ToString(); }
        //    get { return }
        //}

        //public int startCurrent
        //{
        //    //DateTime today = DateTime.Today;

        //    get { return (((DateTime.Today.Date)) - (DateTime.Parse(this.startProcess))).TotalDays; }
        //}

    }
}
