//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowAppsChevron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow_Table
    {
        public int workflow_id { get; set; }
        public string workflow_name { get; set; }
        public string workflow_subject { get; set; }
        public string workflow_pic { get; set; }
        public string workflow_wm { get; set; }
    }
}
